"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const stages=["INTAKE","PROBLEM","MARKET","TECHNOLOGY","REGULATION","EVIDENCE","CONCEPT","MVP","VALIDATION","SPECIFICATION"];
const agents=["PROBLEM","MARKET","TECHNOLOGY","REGULATION"];
const entityFields:any={problem:["statement","severity"],customer:["name","segment","need"],market:["name","geography","tam","sam","som","growthRate"],competitor:["name","url","positioning","strengths","weaknesses"],technology:["name","maturity","description"],regulation:["name","jurisdiction","applicability"]};
const labels:any={statement:"Statement",severity:"Severity",name:"Name",segment:"Segment",need:"Need",geography:"Geography",tam:"TAM",sam:"SAM",som:"SOM",growthRate:"Growth rate",url:"URL",positioning:"Positioning",strengths:"Strengths",weaknesses:"Weaknesses",maturity:"Maturity",description:"Description",jurisdiction:"Jurisdiction",applicability:"Applicability"};

export default function DiscoveryCommandCenter({projectId,initial}:{projectId:string;initial:any}){
 const router=useRouter(); const [d,setD]=useState(initial); const [runs,setRuns]=useState<any[]>([]); const [busy,setBusy]=useState(""); const [agent,setAgent]=useState("PROBLEM"); const [query,setQuery]=useState(""); const [reviewer,setReviewer]=useState(""); const [rationale,setRationale]=useState(""); const [filter,setFilter]=useState("ALL"); const [entity,setEntity]=useState("problem"); const [fields,setFields]=useState<any>({}); const [error,setError]=useState("");
 const refresh=async()=>{const [a,b]=await Promise.all([fetch(`/api/projects/${projectId}/discovery`),fetch(`/api/projects/${projectId}/research`)]);if(a.ok)setD(await a.json());if(b.ok)setRuns(await b.json());};
 useEffect(()=>{refresh()},[projectId]);
 const evidence=useMemo(()=>filter==="ALL"?d.evidence:d.evidence.filter((e:any)=>e.status===filter),[d.evidence,filter]);
 async function post(path:string,body:any){setBusy(path);setError("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error||"Request failed");await refresh();router.refresh();return x}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy("")}}
 async function addEntity(e:React.FormEvent){e.preventDefault();await post(`/api/projects/${projectId}/discovery`,{type:entity,data:fields});setFields({})}
 async function launchAgent(){await post(`/api/projects/${projectId}/research`,{agentType:agent,query:query||`Research ${agent.toLowerCase()} evidence for ${d.project.name}`});setQuery("")}
 async function verifyEvidence(id:string,decision:string){if(!reviewer){setError("Reviewer is required");return}await post(`/api/projects/${projectId}/evidence/${id}/verify`,{reviewer,decision,rationale:rationale||undefined})}
 async function verifyFinding(runId:string,findingId:string,decision:string){if(!reviewer){setError("Reviewer is required");return}await post(`/api/projects/${projectId}/research/${runId}/findings/${findingId}/verify`,{reviewer,decision,rationale:rationale||undefined})}
 async function gate(g:any,status:string){if(!reviewer){setError("Reviewer is required");return}await post(`/api/projects/${projectId}/gates/${g.gate_number}/review`,{reviewer,status,rationale:rationale||undefined})}
 return <div className="command"><section className="section"><div className="hero"><div><div className="eyebrow">{d.project.code}</div><h1>{d.project.name}</h1><p className="subtitle">{d.project.description||"Evidence-first discovery workspace."}</p></div><span className="badge strong">{d.project.current_stage}</span></div><div className="pipeline wide">{stages.map((s,i)=><div className={`stage ${s===d.project.current_stage?"active":""}`} key={s}><strong>{s}</strong><small>{i<stages.indexOf(d.project.current_stage)?"DONE":s===d.project.current_stage?"CURRENT":"NEXT"}</small></div>)}</div></section>
 <section className="section grid three"><div className="card"><div className="label">Evidence</div><div className="metric">{d.evidence.length}</div></div><div className="card"><div className="label">Verified</div><div className="metric">{d.evidence.filter((e:any)=>e.status==="VERIFIED").length}</div></div><div className="card"><div className="label">Human reviews</div><div className="metric">{d.reviews.length}</div></div></section>
 <section className="section two"><div className="card"><h2>Research agents</h2><p className="subtitle">Run provider-neutral research against the configured AI provider. Outputs remain pending until a human accepts them.</p><div className="inline"><select value={agent} onChange={e=>setAgent(e.target.value)}>{agents.map(a=><option key={a}>{a}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Research question or scope" /><button className="button" disabled={!!busy} onClick={launchAgent}>{busy.includes("/research")?"Running…":"Run agent"}</button></div>{runs.length>0&&<div className="runlist">{runs.slice(0,8).map(r=><div className="run" key={r.id}><strong>{r.agent_type}</strong><span>{r.status}</span><small>{r.query}</small>{(r.findings||[]).map((f:any)=><div className="finding" key={f.id}><b>{f.title}</b><p>{f.claim}</p><small>Confidence: {f.confidence??"—"} · {f.evidence_status||"PENDING"}</small>{f.evidence_status!=="VERIFIED"&&<div className="gate-actions"><button onClick={()=>verifyFinding(r.id,f.id,"ACCEPT")}>Accept finding</button><button onClick={()=>verifyFinding(r.id,f.id,"REJECT")}>Reject finding</button></div>}</div>)}</div>)}</div>}</div><div className="card"><h2>Human review</h2><div className="form compact"><label>Reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Name / role" /></label><label>Rationale<textarea rows={2} value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Decision rationale" /></label></div></div></section>
 <section className="section two"><div className="card"><h2>Add discovery record</h2><form className="form compact" onSubmit={addEntity}><label>Entity type<select value={entity} onChange={e=>{setEntity(e.target.value);setFields({})}}>{Object.keys(entityFields).map(x=><option key={x}>{x}</option>)}</select></label>{entityFields[entity].map((f:string)=><label key={f}>{labels[f]}<input required={f==="name"||f==="statement"} value={fields[f]??""} onChange={e=>setFields((v:any)=>({...v,[f]:["tam","sam","som","growthRate","severity"].includes(f)?Number(e.target.value):e.target.value}))} /></label>)}<button className="button" disabled={!!busy}>{busy.includes("discovery")?"Saving…":"Add record"}</button></form></div><div className="card"><h2>Gate Board</h2><div className="gateboard">{d.gates.map((g:any)=><div className={`gate ${g.status.toLowerCase()}`} key={g.id}><div><strong>{g.gate_number}. {g.gate_code}</strong><small>{g.stage}</small></div><span className="badge">{g.status}</span>{g.status!=="ADVANCE"&&g.status!=="REJECT"&&<div className="gate-actions"><button onClick={()=>gate(g,"ADVANCE")}>Advance</button><button onClick={()=>gate(g,"HOLD")}>Hold</button><button onClick={()=>gate(g,"REWORK")}>Rework</button><button onClick={()=>gate(g,"REJECT")}>Reject</button></div>}</div>)}</div></div></section>
 <section className="section"><div className="card"><div className="section-head"><div><h2>Evidence Register</h2><p className="subtitle">Accepted evidence is created only through explicit human verification.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option>{["VERIFIED","DERIVED","DECLARED","SCENARIO","PENDING"].map(x=><option key={x}>{x}</option>)}</select></div><table className="table"><thead><tr><th>Claim</th><th>Status</th><th>Confidence</th><th>Source</th><th>Action</th></tr></thead><tbody>{evidence.map((e:any)=><tr key={e.id}><td><strong>{e.claim}</strong><br/><small>{e.excerpt||""}</small></td><td><span className="badge">{e.status}</span></td><td>{e.confidence??"—"}</td><td>{e.locator||e.source_id||"—"}</td><td>{e.status!=="VERIFIED"?<><button onClick={()=>verifyEvidence(e.id,"ACCEPT")}>Accept</button><button onClick={()=>verifyEvidence(e.id,"REJECT")}>Reject</button></>:"Verified"}</td></tr>)}</tbody></table></div></section>{error&&<div className="error toast">{error}</div>}</div>;
}
